web:
 build: .
 ports:
  - "8000:8000"
  - "3333:3333"
  - "3334:3334"
 links:
  - elk
elk:
 image: sebp/elk
 ports:
  - "5601:5601"
  - "9200:9200"
  - "5000:5000"
  - "5001:5001"
 volumes:
  - 02-tcp-input.conf:/etc/logstash/conf.d/02-tcp-input.conf